<?php 
session_register('itemsEnCesta');
session_register('tot_price');
session_register('totPed');
session_register('cnt');
session_register('userName');
session_register('t1');
session_register('t2');
session_register('t3');
session_register('t4');
session_register('t5');
session_register('t6');
session_register('t7');
session_register('t8');
session_register('t9');
session_register('t10');
session_register('t0');
session_register('t11');
session_register('tpais');
session_register('dety');
session_register('det_base');
session_register('tVale');
session_register('gEnvio');
session_register('miki');
session_register('usr');

?>
